from django.urls import path
from .views import (
    LivroListView,
    LivroDetailView,
    LivroCreateView,
    LivroUpdateView,
    LivroDeleteView,
    EstanteListView,
    EstanteDetailView,
    EstanteCreateView,
    EstanteUpdateView,
    EstanteDeleteView,
    EditoraListView,
    EditoraDetailView,
    EditoraCreateView,
    EditoraUpdateView,
    EditoraDeleteView,
    MembroListView,
    MembroDetailView,
    MembroCreateView,
    MembroUpdateView,
    MembroDeleteView,
    EmprestimoListView,
    EmprestimoDetailView,
    EmprestimoCreateView,
    EmprestimoUpdateView,
    EmprestimoDeleteView,
    MultaListView,
    MultaDetailView,
    MultaCreateView,
    MultaUpdateView,
    MultaDeleteView,
)

urlpatterns = [
    # Livros
    path('livros/', LivroListView.as_view(), name='livro-list'),
    path('livros/criar/', LivroCreateView.as_view(), name='livro-create'),
    path('livros/<int:pk>/', LivroDetailView.as_view(), name='livro-detail'),
    path('livros/<int:pk>/atualizar/', LivroUpdateView.as_view(), name='livro-update'),
    path('livros/<int:pk>/deletar/', LivroDeleteView.as_view(), name='livro-delete'),
    # Estantes
    path('estantes/', EstanteListView.as_view(), name='estante-list'),
    path('estantes/criar/', EstanteCreateView.as_view(), name='estante-create'),
    path('estantes/<int:pk>/', EstanteDetailView.as_view(), name='estante-detail'),
    path('estantes/<int:pk>/atualizar/', EstanteUpdateView.as_view(), name='estante-update'),
    path('estantes/<int:pk>/deletar/', EstanteDeleteView.as_view(), name='estante-delete'),
    # Editoras
    path('editoras/', EditoraListView.as_view(), name='editora-list'),
    path('editoras/criar/', EditoraCreateView.as_view(), name='editora-create'),
    path('editoras/<int:pk>/', EditoraDetailView.as_view(), name='editora-detail'),
    path('editoras/<int:pk>/atualizar/', EditoraUpdateView.as_view(), name='editora-update'),
    path('editoras/<int:pk>/deletar/', EditoraDeleteView.as_view(), name='editora-delete'),
    # Membros
    path('membros/', MembroListView.as_view(), name='membro-list'),
    path('membros/criar/', MembroCreateView.as_view(), name='membro-create'),
    path('membros/<int:pk>/', MembroDetailView.as_view(), name='membro-detail'),
    path('membros/<int:pk>/atualizar/', MembroUpdateView.as_view(), name='membro-update'),
    path('membros/<int:pk>/deletar/', MembroDeleteView.as_view(), name='membro-delete'),
    # Empréstimos
    path('emprestimos/', EmprestimoListView.as_view(), name='emprestimo-list'),
    path('emprestimos/criar/', EmprestimoCreateView.as_view(), name='emprestimo-create'),
    path('emprestimos/<int:pk>/', EmprestimoDetailView.as_view(), name='emprestimo-detail'),
    path('emprestimos/<int:pk>/atualizar/', EmprestimoUpdateView.as_view(), name='emprestimo-update'),
    path('emprestimos/<int:pk>/deletar/', EmprestimoDeleteView.as_view(), name='emprestimo-delete'),
    # Multas
    path('multas/', MultaListView.as_view(), name='multa-list'),
    path('multas/criar/', MultaCreateView.as_view(), name='multa-create'),
    path('multas/<int:pk>/', MultaDetailView.as_view(), name='multa-detail'),
    path('multas/<int:pk>/atualizar/', MultaUpdateView.as_view(), name='multa-update'),
    path('multas/<int:pk>/deletar/', MultaDeleteView.as_view(), name='multa-delete'),
]