# Generated by Django 6.0.3 on 2026-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('paginas', models.PositiveIntegerField()),
                ('ano_publicacao', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('livros', models.ManyToManyField(blank=True, related_name='estantes', to='api.livro')),
            ],
        ),
    ]
