# Generated by Django 6.0.3 on 2026-05-14 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editora_membro_livro_data_cadastro_livro_editora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='membro',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida')], default='ativa', max_length=10)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.membro')),
            ],
        ),
    ]
