# Generated by Django 6.0.3 on 2026-05-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membro_cpf_membro_endereco_membro_user_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='exemplares',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
