# Generated by Django 6.0.3 on 2026-05-22 19:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_livro_exemplares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_multa_dia', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=6)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
            },
        ),
        migrations.DeleteModel(
            name='Estante',
        ),
    ]
